### ISSUE TITLE
Mod - 0 Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [Triplemanus/mod_0_skills#1]
Here’s the checklist. I’m on my phone and it won’t let me do snippets :(

# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [x]  Directories are named correctly.
* [x]  Files are named correctly.
* [ ]  Files and directories are structured correctly.
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [x]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [ ]  Directories and files were named and structured correctly.
* [x]  The attributes chosen for **Class #1** represent states or characteristics.
* [x]  The attributes chosen for **Class #2** represent states or characteristics.
* [x]  The attributes chosen for **Class #3** represent states or characteristics.
* [x]  The methods chosen for **Class #1** represent behaviors or actions.
* [x]  The methods chosen for **Class #2** represent behaviors or actions.
* [x]  The methods chosen for **Class #3** represent behaviors or actions.
* [ ]  Data type (string, integer, boolean, array, hash/object, datetime) were identified correctly for each attribute in all three classes.
* [x]  Individual changes were added and committed separately with a properly formatted commit message.
* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [ ]   Technical Ready
* [x]   Pending
* [ ]   Not Ready

**Comment by timomitchel** [comment]
Good job on the technical assessment @Triplemanus. We want you to make a few changes and then you will be deemed `Technical Ready`. For file and directory structure, go ahead and delete the blank `.md` file that you had with your initial commit. And, move your class files into a directory named `classes`. With regards to your class attributes, anything named plurally tends to represent a collection and would be best stored in an array. Try to keep your naming conventions the same across files. Generally the best convention is for the names of each word in your attributes and methods to begin with a lower case letter as capitalization is usually reserved for class names and types. Go ahead and make these changes with a properly formatted commit message and send us a DM when you have pushed them to Github and have an updated repo to reflect them.
